### ISSUE TITLE
Membership form

### ISSUE THREAD

**Issue by saketp16** [atharva-kathane/Gym-Website#1]
Include membership form through which users can online apply for membership and select time slots and have fee structure . This will also include validation for the input fields.

**Comment by atharva-kathane** [comment]
Yes you can go ahead with this. Make sure to add the form on main page of the website. Also add validation to the form. You can add attributes like name, age, email address , contact no , various programs , fee structure etc.

**Comment by atharva-kathane** [comment]
Your pull request to the project was accepted and merged. Thank you for contributing to the project.
